#! /bin/csh -f

# v1.0 Zerun Thu 29 Feb 16:16:23 CET 2024
# - klayout batch mode running lvs
source ../.setPDK.csh
### set your gds and topcell ###
#set gds_path = croc_chip.gds
set gds_path     = chip.gds
set netlist_path = chip.spi
set topcell      = chip
################################
#Usage:
#    run_lvs.py (--help| -h)
#    run_lvs.py (--layout=<layout_path>) (--netlist=<netlist_path>)
#Options:
#    --help -h                   Displays this help message.
#    --layout=<layout_path>      Specifies the file path of the input GDS file.
#    --netlist=<netlist_path>    Specifies the file path of the input netlist file.
#    --run_dir=<run_dir_path>    Run directory to save all the generated results [default: pwd]
#    --topcell=<topcell_name>    Specifies the name of the top cell to be used.
#    --run_mode=<run_mode>       Selects the allowed KLayout mode. (flat, deep). [default: deep]
#    --no_net_names              Omits net names in the extracted netlist.
#    --spice_comments            Includes netlist comments in the extracted netlist.
#    --net_only                  Generates netlist objects only in the extracted netlist.
#    --no_simplify               Disables simplification for both layout and schematic.
#    --no_series_res             Prevents simplification of series resistors for both layout and schematic.
#    --no_parallel_res           Prevents simplification of parallel resistors for both layout and schematic.
#    --combine_devices           Enables device combination for both layout and schematic netlists.
#    --top_lvl_pins              Creates pins for top-level circuits in both layout and schematic netlists.
#    --purge                     Removes unused nets from both layout and schematic netlists.
#    --purge_nets                Purges floating nets from both layout and schematic netlists.
#    --verbose                   Enables detailed rule execution logs for debugging purposes.
#    --allow_unmatched_ports     Allows unmatched or improperly labeled ports(pins) in the top-level circuit.

time oseda -2026.04 python3 $IHP_TECH/klayout/tech/lvs/run_lvs.py \
 --layout=$gds_path \
 --netlist=$netlist_path \
 --topcell=$topcell \
 --run_dir ./lvs
