#! /bin/csh -f

# v0.2 - <bmuheim@ethz.ch> - Wed Oct  2 14:23:41 CEST 2024
#  - starting klayout fron the oseda conaner
# v0.1 - <bmuheim@ethz.ch> - Tue Mar 21 16:35:48 CET 2023
#  - new

source ../.setPDK.csh

oseda -2026.04 klayout -l ${technology}.lyp -c .klayout/klayoutrc -e $* &

